plugins {
    id 'application'
    id 'java'
}

group = 'com.soka.kelompok5'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.cloudsimplus:cloudsim-plus:8.0.0'
}

application {
    mainClass = 'com.soka.kelompok5.TopsisCloudSim'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('run') {
    jvmArgs = ['--add-opens', 'java.base/java.lang=ALL-UNNAMED', '--add-opens', 'java.base/java.util=ALL-UNNAMED']
}
